Global seed set to 1234
Global seed set to 1234
/home/taufikmh/miniconda3/envs/my_env_plot/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py:352: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(
Traceback (most recent call last):
  File "./Example-5.py", line 112, in <module>
    trainer = Trainer(
  File "/home/taufikmh/miniconda3/envs/my_env_plot/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/taufikmh/miniconda3/envs/my_env_plot/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/home/taufikmh/miniconda3/envs/my_env_plot/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 211, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/home/taufikmh/miniconda3/envs/my_env_plot/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 517, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
pytorch_lightning.utilities.exceptions.MisconfigurationException: No supported gpu backend found!