
Global seed set to 1234
Traceback (most recent call last):
  File "./Example-5.py", line 39, in <module>
    data = HCEikonalPINNsData(dict_args, batch_size=int(nx*nz*ns)//200)
  File "/home/taufikmh/KAUST/fall_2022/external_repos/copy-HCPINNsEikonal-dev/src/hcpinnseikonal/distributed.py", line 562, in __init__
    X, Y, Z, SX, SY, SZ, taud, taudx, taudy, T0, px0, py0, pz0, index, self.sx, self.sy, self.sz, rx, ry, rz, self.vel3d, self.id_rec, self.id_sou = setup_medium(args)
  File "/home/taufikmh/KAUST/fall_2022/external_repos/copy-HCPINNsEikonal-dev/src/hcpinnseikonal/distributed.py", line 440, in setup_medium
    vs = vel3d[np.round(SZ/deltaz).astype(int),np.round(SY/deltay).astype(int),np.round(SX/deltax).astype(int)]
IndexError: index 320 is out of bounds for axis 1 with size 100